version: "3"
services:
  blog:
    environment:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_AUTO_INSTALL: true
    ports:
      - 4000:4000
    volumes:
      - .:/blog
    image: ruby
    command: bundle exec jekyll serve -l -H 0.0.0.0
    working_dir: /blog
    entrypoint: "./entrypoint.sh"
